@echo off
REM ****************************************************************************
REM Vivado (TM) v2025.2.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Apr 14 14:31:53 +0530 2026
REM SW Build 6403652 on Thu Mar 19 19:48:24 GMT 2026
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
set SIM_VER_XSIM=
set GCC_VER_XSIM=9.3.0
REM simulate design
echo "xsim UART_TOP_tb_behav -key {Behavioral:sim_1:Functional:UART_TOP_tb} -tclbatch UART_TOP_tb.tcl -log simulate.log"
call xsim  UART_TOP_tb_behav -key {Behavioral:sim_1:Functional:UART_TOP_tb} -tclbatch UART_TOP_tb.tcl -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
